name: archivea_reader

description: Archivea mobile reader (Android first, iOS ready)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  syncfusion_flutter_pdfviewer: ^28.1.35

flutter:
  uses-material-design: true
